name: do-stuff

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  pull_request_target:
      types:
      - closed
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Force do stuff'

jobs:
  run-fancy-thing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: do the thing
        id: fancy-things
        uses: Raganhar/nup-github-action-jira-transition@main
        env:
          GREETINGS: 'Hello, .NET developers!' # ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: "${{ toJson(github) }}"
        with:
          from: text
          text: NIC-6 | will search in branch name
          jira-api-key: ${{ github.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ github.JIRA_BASE_URL }}
          jira-user: ${{ github.JIRA_USER_EMAIL }}