name: transition-jira-issues-on-release-push

on:
  push:
      branches:
      - release  
      
jobs:
  transition-jira-issues-on-push:
    runs-on: ubuntu-latest

    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: do the thing
        id: fancy-things
        uses: Raganhar/nup-github-action-jira-transition@main
        env:
          GITHUB_CONTEXT: "${{ toJson(github) }}"
        with:
          # from: text
          # text: NIC-6 | will search in branch name
          jira-api-key: ${{ secrets.JIRA_API_TOKEN }}
          jira-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user: ${{ secrets.JIRA_USER_EMAIL }}
          main-jira-transition: done
          release-jira-transition: in progress
          branch_to_compare_to: main